### ISSUE TITLE
Logo Design For Expense Manager

### ISSUE THREAD

**Issue by zularizal** [sabiou/depensy#8]
Hi @sabiou , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by sabiou** [comment]
Hi @zularizal , I'm glad you're interested and I'm open for contribution. You're welcome :smiley:

**Comment by sabiou** [comment]
By the way I want to change the name of the app. If you have any suggestion feel free :sweat_smile:  @zularizal

**Comment by zularizal** [comment]
What is the new name for this app? @sabiou

**Comment by sabiou** [comment]
@zularizal depensy .. have you any suggestion?

**Comment by zularizal** [comment]
I like it. A good name and easy to remember.  Later I will show it when it's finished. @sabiou

**Comment by sabiou** [comment]
Good. :+1:

**Comment by zularizal** [comment]
Hi @sabiou , here are some proposal logos for your project. The logos are inspired by a chart, letter D, wallet and dollar currency.

What do you think, which do you like? And what color do you like?
If there is something you want to change, let me know

![bitmap](https://user-images.githubusercontent.com/38547278/55275331-3deff500-5317-11e9-861b-3c813cbad1ed.png)

**Comment by sabiou** [comment]
Hi bro, I think the last one is good for the project.

**Comment by zularizal** [comment]
Okay, I will make a pull request.

**Comment by zularizal** [comment]
Hi @sabiou , I have sent a pull request for you. #10 

And also I have uploaded the logo to the drive. Check this link.

https://drive.google.com/open?id=1QgS33Aoh_HWBpGEWRgzsbrXMQON1ULde

**Comment by sabiou** [comment]
Thanks bro I will look for it.

**Comment by sabiou** [comment]
And I would like to have a chat with you.. Are you on Telegram?

**Comment by zularizal** [comment]
Sure bro.. This is my link https://t.me/zularizal

**Comment by zularizal** [comment]
If you need a logo for another project, don't hesitate to contact me. Because I did not take the fees to make it
